issues/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.new , name = "index" ),
    url(r'^new/$' ,views.new  , name="newissue"),
    url(r'^(?P<issue_id>[0-9]+)/$' ,views.result  , name="getissue"),
]

ntsw/urls.py
from django.conf.urls import url ,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^issues/', include('issues.urls') ),
    url(r'^$', include('issues.urls') ),

]

issues/models.py
from django.db import models



    

# Create your models here.
class Issue(models.Model):
    system_account = models.CharField(max_length =30)
    conn_email = models.CharField(max_length =30)
    conn2_email = models.CharField(max_length =30)
    tags = models.CharField(max_length =200,blank=True)
    public = models.BooleanField( default=True )
    title = models.CharField(max_length =60)
    description_public = models.TextField( blank=True )    
    description = models.TextField( blank=True )
    issue_time = models.DateTimeField()
    issue_submit_time = models.DateTimeField(  )
    #job = models.ForeignKey( JobIssue , on_delete=models.CASCADE  , blank=True , null=True )
    #jobs = models.ManyToManyField( JobIssue , verbose_name="list of issue jobs" )
    def __str__(self):
        return self.title

class JobIssue(models.Model):
    jobid = models.IntegerField()
    software = models.CharField(max_length =30,blank=True )
    submit_ln = models.CharField(max_length =30,blank=True )
    workdir = models.CharField(max_length =30,blank=True )
    nodelist = models.CharField(max_length =30,blank=True )
    submit_env = models.CharField(max_length =200,blank=True )
    submit_cmd = models.CharField(max_length =200,blank=True )
    submit_time = models.CharField(max_length =200,blank=True )
    error_time = models.DateTimeField(blank=True ,null=True)
    issue = models.ForeignKey( Issue , on_delete=models.CASCADE  , blank=True , null=True )
    
    
class Response(models.Model):
    name = models.CharField(max_length =30)
    submit_time = models.DateTimeField()
    description_public = models.TextField()
    description = models.TextField()
    
    

issues/views.py
from django.shortcuts import render
from django.http import HttpResponse , FileResponse , StreamingHttpResponse ,HttpResponseRedirect ,HttpRequest
from django.urls import reverse
from django import forms
from django.forms import ModelForm
from .models import Issue , JobIssue
from django.core import serializers
from datetime import datetime
import smtplib
from email.mime.text import MIMEText
import hashlib
from django.conf import settings

email_conn_class = settings.ISSUE_CONF['email_conn_class']


class IssueForm(ModelForm):
    title = forms.CharField( label = '问题标题 Issue title' ,help_text='glyphicon glyphicon-pencil' , widget=forms.TextInput( attrs={'class' :'form-control' , 'placeholder' : '问题标题' } )  )
    system_account = forms.CharField( label = '系统账号 System Account' ,help_text='glyphicon glyphicon-user' , widget=forms.TextInput( attrs={'class' :'form-control' , 'placeholder' : '系统账号' } ) )
    conn_email = forms.EmailField( label = '联系邮件 E-Mail' ,help_text='glyphicon glyphicon-envelope' , widget=forms.EmailInput( attrs={'class' :'form-control' , 'placeholder' : 'E-Mail Address' } ) ) 
    #issue_time = forms.DateTimeField(  label = 'Issue time' ,help_text='glyphicon glyphicon-time' , widget=forms.DateTimeInput( format="%Y-%m-%dT%H:%M", attrs={'class' :'form-control' , 'placeholder' : 'E-Mail Address' , 'type' : 'datetime-local' } )   ) #forms.DateTimeField( required=True , input_formats="%Y-%m-%dT%H:%M" )
    issue_time = forms.CharField(  label = '问题发生时间 Issue time' ,help_text='glyphicon glyphicon-time' , widget=forms.DateTimeInput( format="%Y-%m-%dT%H:%M", attrs={'class' :'form-control' , 'placeholder' : '问题发生的时间' , 'type' : 'datetime-local' } )   ) #forms.DateTimeField( required=True , input_formats="%Y-%m-%dT%H:%M" )
    conn2_email = forms.TypedChoiceField( label='问题分类 Issue Class'  ,  empty_value="..." ,choices=email_conn_class ,  help_text='glyphicon glyphicon-list',widget=forms.Select( 
        attrs={
            'class' :'form-control'
        }
    ))
    public = forms.ChoiceField(label='是否公开此问题 Do you want to public this issue ?'  , choices=(
        ( True , "True" ) ,
        ( False, "False") ,
    ) , help_text='none' , widget=forms.RadioSelect(     ) )
    description_public = forms.CharField( required=False  ,  label='可公开问题信息 Public Description' , widget=forms.Textarea( attrs={'class' :'form-control' , 'placeholder' : '可公开的问题描述' } )  )
    description = forms.CharField( required=False ,  label='私密问题信息 Private Description' , widget=forms.Textarea( attrs={'class' :'form-control' , 'placeholder' : '其他问题描述' } )  )
    isjob = forms.ChoiceField(label='是否是作业问题 Is this a job issue ?'  , choices=(
        ( True , "True" ) ,
        ( False, "False") ,
    ) , help_text='none' , widget=forms.RadioSelect(     ) )
 
    class Meta :
        model = Issue
        fields = [       'title' , 'system_account' ,  'conn_email',
                    'conn2_email' , # 'tags' ,
                     'public' , 'description_public' ,
                     'description' ,
                   'issue_time' ,
 ]

class JobIssueForm(ModelForm) :
    jobid = forms.CharField( required=False ,label = '作业id Job ID' ,help_text='glyphicon glyphicon-pencil' , widget=forms.TextInput( attrs={'class' :'form-control' , 'placeholder' : '作业ID号(*)' } )  )
    software = forms.CharField( required=False , label = '所用软件 software' ,help_text='glyphicon glyphicon-pencil' , widget=forms.TextInput( attrs={'class' :'form-control' , 'placeholder' : '使用的软件' } )  )
    submit_ln = forms.CharField(required=False , label = '提交节点 submit node' ,help_text='glyphicon glyphicon-pencil' , widget=forms.TextInput( attrs={'class' :'form-control' , 'placeholder' : '提交作业的节点' } )  )
    workdir = forms.CharField(required=False , label = '工作路径 work dir' ,help_text='glyphicon glyphicon-pencil' , widget=forms.TextInput( attrs={'class' :'form-control' , 'placeholder' : '工作路径' } )  )
    submit_env = forms.CharField( required=False ,label = '作业运行环境 Job Env' ,help_text='glyphicon glyphicon-pencil' , widget=forms.TextInput( attrs={'class' :'form-control' , 'placeholder' : '作业环境设置' } )  )
    submit_cmd = forms.CharField( required=False ,label = '作业命令 Job CMD' ,help_text='glyphicon glyphicon-pencil' , widget=forms.TextInput( attrs={'class' :'form-control' , 'placeholder' : '作业提交命令' } )  )
    class Meta :
        model = JobIssue
        fields = [   'jobid' ,  'software' ,
    'submit_ln' , 'workdir',   # 'nodelist',
     'submit_env', 'submit_cmd', # 'submit_time',
   # 'error_time'  , 
   ] 

    


# Create your views here.


email_host = settings.ISSUE_CONF['email_host']
email_user = settings.ISSUE_CONF['email_user']
email_pass = settings.ISSUE_CONF['email_pass']
#email_ = ''

def email_send( title , recivers , content  ) :
    try :
        title = "[AutoMail][NewIssue]" + title 
        msg = MIMEText(content )
        msg['Subject'] = title
        msg['From'] = email_user
        msg['To'] = ','.join(recivers)
        smtp = smtplib.SMTP( email_host )
        smtp.login( email_user , email_pass  )
        smtp.sendmail(email_user , recivers , msg.as_string() )
        smtp.close()
    except Exception as e :
        print("email_send error:" , e )

def email_send_html( title , recivers , content  ) :
    try :
        title = "[AutoMail][NewIssue]" + title 
        msg = MIMEText(content , "HTML" , "utf-8")
        msg['Subject'] = title
        msg['From'] = email_user
        msg['To'] = ','.join(recivers)
        smtp = smtplib.SMTP( email_host )
        smtp.login( email_user , email_pass  )
        smtp.sendmail(email_user , recivers , msg.as_string() )
        smtp.close()
    except Exception as e :
        print("email_send error:" , e )

def index(request) :
    return HttpResponse("hello!")

def new(request):
    #return HttpResponse("hello! try to create new issue. ")
    message_error = ""
    if request.method == 'POST' :
        form = IssueForm(request.POST ,prefix = 'issue' )
        jform = JobIssueForm( request.POST , prefix = 'jobissue' )
        #print(request.POST)
        #print(form)
        if form.is_valid():
            print("form is valid")
            job = None
            err = False
            #print(form.cleaned_data["isjob"] , type( form.cleaned_data["isjob"] ))
            if form.cleaned_data["isjob"] == "True" :
                if jform.is_valid():
                    print("job is valid")
                    job = jform.save( commit =False )
                    print(  serializers.serialize( "json" , [job] ) )
                    if not job.jobid:
                        message_error="need jobid!"
                        err = True 
                else:
                    err = True
            if not err :
                newissue = form.save( commit=False )
                print("time" ,newissue.issue_time  )
                #try :
                #    newissue.issue_time = datetime.strptime( form.cleaned_data["issue_time"] ,      "%Y-%m-%dT%H:%M" )
                #except Exception as e :
                #    pass
                newissue.issue_submit_time = datetime.now()
                newissue.save()
                jsonstring = ""
                if job :
                    job.issue = newissue 
                    job.save()
                    #jsonstring += serializers.serialize( "json" , [job] )
                #jsonstring += serializers.serialize( "json" , [newissue] )
                print( "Sucess return " )
                issue_token = issue_gentoken( newissue.pk  )
                # try to send email 
                newrequest = HttpRequest()
                newrequest.method = "GET"
                newrequest.GET['token'] = issue_token
                newrequest.user = request.user
                resp = result_email(newrequest , newissue.pk , token=issue_token)
                content = resp.content.decode("utf-8")  #content = "new issue  %d \n url : %s \n json: %s" % ( newissue.pk , issue_url , resp.content.decode("utf-8") )
                email_send_html( newissue.title , [ newissue.conn_email , newissue.conn2_email  ] , content  )
                return HttpResponseRedirect( reverse( 'getissue' , args=( newissue.pk ,) ) + '?token=' + issue_token   )

        else :
            pass
        #if jform.is_valid():
        #    print("jform is valid")
    else :
        form = IssueForm( prefix = 'issue'  )
        jform = JobIssueForm( prefix = 'jobissue' )
    print( form.is_bound )
    #form['title'].classx = 'aaa'
    #print( form['title'].css_classes())
    return render(request , 'issues/new.html' , {'form':form , 'jform' : jform , 'message_error' : message_error }  )

def issue_gentoken(issue_id) :
    issue = Issue .objects.get(pk= issue_id)
    issue_json =  serializers.serialize( "json" , [issue] ) 
    m2 = hashlib.md5()
    m2.update( (issue_json ).encode('utf-8'))
    issue_md5 = m2.hexdigest()
    return issue_md5[:5]

def result_email(request , issue_id , token=None):
    issue = Issue .objects.get(pk= issue_id)
    job = JobIssue.objects.filter( issue=issue_id )
    if len( job ):
        job = job[0]
    else :
        job = None
    return render(request , 'issues/issue_email.html' , {'issue':issue , 'job':job , 'token':token }  )



def result(request , issue_id ):
    issue = Issue .objects.filter(pk= issue_id)
    job = JobIssue.objects.filter( issue=issue_id )
    if len( issue ):
        issue = issue[0]
    else :
        issue = None 
    if len( job ):
        job = job[0]
    else :
        job = None

    token = request.GET.get('token','')
    token_pass = False
    user_pass = False 
    if token and issue :
        issue_token = issue_gentoken( issue_id )
        print(issue_token)
        if token == issue_token :
            print("token pass")
            token_pass = True
    if  request.user.is_authenticated() :
        if ( request.user.is_staff ) :
            user_pass = True 
    private_right = user_pass or token_pass

issues/templates/issues/issue.html
{% extends "base.html" %}
{% load markdown_deux_tags %}

{% block legend %}
 issue {{ issue.pk }} :  {{ issue.title }} 
{% endblock %}

{% block content %}



<div class="well form-horizontal" >
<fieldset>
{{  private_right }}
  {% if private_right %}

  <!-- issue system account  -->
<div class="form-group" ><label class="col-md-4 control-label"> System Account </label>  
  <div class="col-md-4 inputGroupContainer"><div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
<span  class="form-control">{{ issue.system_account }} </span>
</div></div></div>
<!-- issue conn_email  -->
<div class="form-group" ><label class="col-md-4 control-label"> Conn Email </label>  
  <div class="col-md-4 inputGroupContainer"><div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-envelope"></i></span>
<span  class="form-control">{{ issue.conn_email }} </span>
</div></div></div>



  {% else %}
  <h2> Private infos are not available for you ! </h2> 
  {% endif %}


<!-- issue tags  -->
<div class="form-group" ><label class="col-md-4 control-label"> tags </label>  
  <div class="col-md-4 inputGroupContainer"><div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-tag"></i></span>
<span  class="form-control">{{ issue.tags }} </span>
</div></div></div>

<!-- issue time  -->
<div class="form-group" ><label class="col-md-4 control-label"> time </label>  
  <div class="col-md-4 inputGroupContainer"><div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
<span  class="form-control">{{ issue.issue_time }} </span>
</div></div></div>


<!-- issue submit time  -->
<div class="form-group" ><label class="col-md-4 control-label"> submit time </label>  
  <div class="col-md-4 inputGroupContainer"><div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-time"></i></span>
<span  class="form-control">{{ issue.issue_submit_time }} </span>
</div></div></div>

<!-- job infos -->
{% if job and private_right %}
 

<!-- issue jobid  -->
<div class="form-group" ><label class="col-md-4 control-label"> job id </label>  
  <div class="col-md-4 inputGroupContainer"><div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
<span  class="form-control">{{ job.jobid }} </span>
</div></div></div>

<!-- issue software  -->
{% if job.software  %}
<div class="form-group" ><label class="col-md-4 control-label"> software </label>  
  <div class="col-md-4 inputGroupContainer"><div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
<span  class="form-control">{{ job.software }} </span>
</div></div></div>
{% endif %}
<!-- issue  submit node -->
{% if job.submit_ln  %}

<div class="form-group" ><label class="col-md-4 control-label"> submit node </label>  
  <div class="col-md-4 inputGroupContainer"><div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
<span  class="form-control">{{ job.submit_ln }} </span>
</div></div></div>
{% endif %}

<!-- issue jobid  -->
{% if job.workdir  %}

<div class="form-group" ><label class="col-md-4 control-label"> work dir </label>  
  <div class="col-md-4 inputGroupContainer"><div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
<span  class="form-control">{{ job.workdir }} </span>
</div></div></div>
{% endif %}

<!-- issue jobid  -->
{% if job.submit_env  %}

<div class="form-group" ><label class="col-md-4 control-label"> job env </label>  
  <div class="col-md-4 inputGroupContainer"><div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
<span  class="form-control">{{ job.submit_env }} </span>
</div></div></div>
{% endif %}

<!-- issue jobid  -->
{% if job.submit_cmd  %}

<div class="form-group" ><label class="col-md-4 control-label"> submit cmd </label>  
  <div class="col-md-4 inputGroupContainer"><div class="input-group">
    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
<span  class="form-control">{{ job.submit_cmd }} </span>
</div></div></div>
{% endif %}


{% endif %}
<!-- job infos end -->



{% if issue.public %}
<!-- issue tags  -->
<h2 > description public :</h2>  <br>

<div class="bg-warning">
  <code class="col-md-12 bg-warning text-muted">
  {{ issue.description_public |markdown }} 
  </code>
</div>
{% endif %}

<!-- issue description  -->
  {% if private_right %}

<h2 > description :</h2>  <br>

<div class="bg-warning">
  <code class="col-md-12 bg-warning text-muted ">
  {{ issue.description |markdown }} 
  </code>
</div>
  {% endif %}





<!-- outer div end  -->
</fieldset></div>

{% endblock %}

{% block on_ready %}

{% endblock %}

   

issues/templates/issues/issue_email.html
{% load markdown_deux_tags %}

{% block legend %}
<h1> issue {{ issue.pk }} :  {{ issue.title }} </h1>
<h2> token : {{ token }} </h2> 
{% endblock %}


<table border=1>



  <!-- issue system account  -->
  <tr>
    <td>
      <label class="col-md-4 control-label"> System Account </label>  
    </td>
<td>
<span  class="form-control">{{ issue.system_account }} </span>
</td>
  </tr>
<!-- issue conn_email  -->
  <tr>
    <td>
      <label class="col-md-4 control-label"> Conn Email </label>  
    </td>
<td>
<span  class="form-control">{{ issue.conn_email }} </span>
</td>
  </tr>
<!-- issue tags  -->
  <tr>
    <td>
      <label class="col-md-4 control-label"> tags </label>  
    </td>
<td>
<span  class="form-control">{{ issue.tags }} </span>
</td>
  </tr>



<!-- issue time  -->
  <tr>
    <td>
      <label class="col-md-4 control-label"> time</label>  
    </td>
<td>
<span  class="form-control">{{ issue.issue_time }} </span>
</td>
  </tr>





<!-- issue submit time  -->
  <tr>
    <td>
      <label class="col-md-4 control-label"> submit time</label>  
    </td>
<td>
<span  class="form-control">{{ issue.issue_submit_time }} </span>
</td>
  </tr>


<!-- job infos -->
 {% if job %}

<!-- issue jobid  -->
  <tr>
    <td>
      <label class="col-md-4 control-label"> job id</label>  
    </td>
<td>
<span  class="form-control">{{ job.jobid }}  </span>
</td>
  </tr>



<!-- issue software  -->



{% if job.software  %}
  <tr>
    <td>
      <label class="col-md-4 control-label"> software</label>  
    </td>
<td>
<span  class="form-control">{{ job.software }}  </span>
</td>
  </tr>
{% endif %}
<!-- issue  submit node -->
{% if job.submit_ln  %}

  <tr>
    <td>
      <label class="col-md-4 control-label"> submit node</label>  
    </td>
<td>
<span  class="form-control">{{ job.submit_ln }}  </span>
</td>
  </tr>

{% endif %}

<!-- issue jobid  -->
{% if job.workdir  %}

  <tr>
    <td>
      <label class="col-md-4 control-label"> work dir</label>  
    </td>
<td>
<span  class="form-control">{{ job.workdir }}  </span>
</td>
  </tr>


{% endif %}

<!-- issue jobid  -->
{% if job.submit_env  %}

  <tr>
    <td>
      <label class="col-md-4 control-label"> job env </label>  
    </td>
<td>
<span  class="form-control">{{ job.submit_env}}  </span>
</td>
  </tr>


{% endif %}

<!-- issue jobid  -->
{% if job.submit_cmd  %}

  <tr>
    <td>
      <label class="col-md-4 control-label"> job cmd </label>  
    </td>
<td>
<span  class="form-control">{{ job.submit_cmd}}  </span>
</td>
  </tr>


{% endif %}


{% endif %}
<!-- job infos end -->

</table>


<!-- issue tags  -->
<h2 > description public :</h2>  <br>

<div class="bg-warning">
  <code class="col-md-12 bg-warning text-muted">
  {{ issue.description_public |markdown }} 
  </code>
</div>

<!-- issue description  -->

<h2 > description :</h2>  <br>

<div class="bg-warning">
  <code class="col-md-12 bg-warning text-muted ">
  {{ issue.description |markdown }} 
  </code>
</div>


<!-- outer div end  -->



   

issues/templates/issues/new.html
{% extends "base_form.html" %}

{% block legend %}
Creat a new issue
{% endblock %}

{% block content_form %}



<form action="" method="POST">
{% csrf_token %}

{% for field in form.visible_fields %}

<div class="form-group" id="div_{{ field.name  }}">
  <label class="col-md-4 control-label"> {{ field.label_tag }} </label>  
        {{ field.errors }}
  <div class="col-md-4 inputGroupContainer">
  <div class="input-group">
      {% if field.help_text %}
{% if field.help_text == "none" %}
{% else %}
  <span class="input-group-addon"><i class="{{ field.help_text }}"></i></span>
 {% endif %}
  {% else %}
    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  {% endif %}
  {{ field }}
</div>
  </div>
</div>


{% endfor %}




<div id="jobdiv" style="display: none;">

<!-- -->
{% for field in jform.visible_fields %}
<div class="form-group" id="div_{{ field.name  }}">
  <label class="col-md-4 control-label"> {{ field.label_tag }} </label>  
  <div class="col-md-4 inputGroupContainer">
  <div class="input-group">
      {% if field.help_text %}
{% if field.help_text == "none" %}
{% else %}
  <span class="input-group-addon"><i class="{{ field.help_text }}"></i></span>
 {% endif %}
  {% else %}
    <span class="input-group-addon"><i class="glyphicon glyphicon-pencil"></i></span>
  {% endif %}
  {{ field.errors }}
  {{ field }}
</div>
  </div>
</div>


{% endfor %}


<!-- -->


 
</div>  <!-- div jobdiv end -->

{% if message_error %}
<div >
<button class="btn btn-danger btn-lg focus ">{{ message_error }}  </button>
</div>
{% endif%}

<div class="form-group">
  <label class="col-md-4 control-label"></label>
  <div class="col-md-4">
    <button type="submit" class="btn btn-warning">Send <span class="glyphicon glyphicon-send"></span></button>
  </div>
  <!--div class="col-md-4">
    <a id="save" href="#" class="btn btn-warning">save <span class="glyphicon glyphicon-send"></span></a>
  </div-->
</div>


</form>


{% endblock %}


{% block on_ready %}

 
/* var regPub = $("#id_issue-description_public");*/
var regPub = $("#div_description_public");


regPub.hide();

        $("input[name='issue-public']").change(function(){
            that = $("input[name='issue-public']:checked");
            console.log( that.val() );
            if(that.val() == "True" ){
                regPub.show();
            }else{
                regPub.hide();
            }
        });
$("input[name='issue-public']").trigger("change");

 var regjobissue = $("#jobdiv");
        $("input[name='issue-isjob']").change(function(){
            var that = $("input[name='issue-isjob']:checked");     
            if(that.val() == "True"){
                regjobissue.show();
            }else{
                regjobissue.hide();
            }
        });
$("input[name='issue-isjob']").trigger("change");




{% endblock %}

   